import { mailEditorIsOpen, MAIL_WORKSPACE_VIEWS } from '../features/personal/mail-workspace.ts'
import type { MailFilters } from '../features/personal/native-mail.ts'
import { nativeMail, mailWorkspace } from '../store/personal.ts'
import { ok, fail, type OsCommand } from '../store/os-commands.ts'

export const nativeMailCommands: readonly OsCommand[] = [
  { id: 'personal.nativeMail.select', title: 'Leer hilo de correo', description: 'Leer sin cambiar el buzón ni marcarlo como visto.', tier: 'read', args: [{ name: 'clave', type: 'string', required: true, description: 'Clave MAIL' }, { name: 'limit', type: 'number', description: 'Mensajes recientes, hasta 25' }],
    run: async ({ clave, limit }) => { await nativeMail.select(String(clave), Math.min(25, Math.max(1, Number(limit ?? 10)))); const error = nativeMail.state.get().detailError; return error ? fail(error) : ok('Hilo abierto.') } },
  { id: 'personal.nativeMail.filter', title: 'Filtrar correo', description: 'Aplicar filtros a la fuente de correo existente.', tier: 'read', hidden: true, args: [{ name: 'filters', type: 'string', required: true, description: 'Filtros JSON' }],
    run: async ({ filters }) => { const values = JSON.parse(String(filters)) as Partial<MailFilters>; if (!values || typeof values !== 'object' || Object.keys(values).some(key => !(key in nativeMail.state.get().filters))) return fail('Filtro de correo inválido.'); await nativeMail.filter(values); const error = nativeMail.state.get().error; return error ? fail(error) : ok('Filtros aplicados.') } },
  { id: 'personal.nativeMail.legacy', title: 'Abrir vista original de correo', description: 'Continuar con el mismo hilo y borrador en las aprobaciones del servicio original.', tier: 'act', args: [{ name: 'view', type: 'string', enum: ['actual', ...Object.keys(MAIL_WORKSPACE_VIEWS)], description: 'Vista; actual conserva el borrador y el hilo seleccionados' }],
    run: async ({ view }) => { const route = nativeMail.handoffRoute(); await mailWorkspace.navigate(view && view !== 'actual' ? `/${String(view)}` : route); if (mailWorkspace.state.get().error) return fail(mailWorkspace.state.get().error!); nativeMail.setLegacy(true); return ok('Vista original abierta. Las aprobaciones se realizan allí.') } },
  { id: 'personal.mailWorkspace.legacyReload', title: 'Recargar vista original', description: 'Actualizar la vista de compatibilidad.', tier: 'read', args: [], run: async () => { await mailWorkspace.reload(); return mailWorkspace.state.get().error ? fail(mailWorkspace.state.get().error!) : ok('Vista original recargada.') } },
  { id: 'personal.nativeMail.return', title: 'Volver al correo de Herald', description: 'Volver al lector nativo y recuperar el borrador guardado.', tier: 'read', args: [], run: async () => { if (mailEditorIsOpen(mailWorkspace.state.get())) return fail('Cierra el editor de la vista original para volver a Herald.'); nativeMail.setLegacy(false); await nativeMail.resumeCompose(); await nativeMail.load(); return ok('Correo de Herald abierto.') } },
  { id: 'personal.nativeMail.update', title: 'Clasificar el hilo', description: 'Guardar estado, categoría o prioridad en la base de correo.', tier: 'mutate', args: [{ name: 'field', type: 'string', required: true, enum: ['estado', 'categoria', 'prioridad'], description: 'Campo' }, { name: 'value', type: 'string', required: true, description: 'Valor' }], run: async ({ field, value }) => { await nativeMail.updateItem(String(field), String(value)); return ok('Clasificación guardada y verificada.') } },
  { id: 'personal.nativeMail.compose', title: 'Redactar correo', description: 'Abrir un borrador local; no envía.', tier: 'mutate', args: [{ name: 'mode', type: 'string', enum: ['nuevo', 'responder', 'responder_todos', 'reenviar'], description: 'Modo' }, { name: 'suggested', type: 'boolean', description: 'Usar el borrador sugerido' }], run: async ({ mode, suggested }, context) => { if (context.source !== 'ui') return fail('Abre el editor desde Correo.'); await nativeMail.openCompose(String(mode ?? 'nuevo'), mode && mode !== 'nuevo' ? nativeMail.state.get().thread?.item.clave : undefined, Boolean(suggested)); return ok('Borrador local abierto.') } },
  { id: 'personal.nativeMail.save', title: 'Guardar borrador local', description: 'Guardar y releer el borrador actual.', tier: 'mutate', args: [], run: async (_, context) => { if (context.source !== 'ui') return fail('Guarda el borrador desde su editor.'); await nativeMail.saveCompose(); return ok(nativeMail.state.get().dirty ? 'La versión anterior se guardó. Hay cambios más recientes pendientes.' : 'Borrador guardado y verificado.') } },
  { id: 'personal.nativeMail.close', title: 'Cerrar redactor', description: 'Cerrar solo si no hay cambios pendientes. El borrador sigue en el servicio.', tier: 'act', args: [], run: () => { nativeMail.closeCompose(); return ok('Editor cerrado; el borrador guardado se conserva.') } },
  { id: 'personal.nativeMail.draft', title: 'Preparar borrador con el redactor', description: 'Usar el redactor y revisor existentes. Solo guarda un borrador local.', tier: 'mutate', args: [{ name: 'instruction', type: 'string', description: 'Qué debe decir' }, { name: 'mode', type: 'string', enum: ['generar', 'ajustar', 'regenerar', 'anterior', 'siguiente'], description: 'Acción del borrador' }, { name: 'force', type: 'boolean', description: 'Redactar aunque vaya dirigido a otra persona' }], run: async ({ instruction, mode, force }, context) => { if (context.source !== 'ui') return fail('Usa el redactor desde Correo para revisar el resultado.'); await nativeMail.draft(String(instruction ?? ''), (mode ?? 'generar') as 'generar', Boolean(force)); return ok('Borrador local actualizado. Revisa texto y destinatarios.') } }
]
